micronaut:
  application:
    name: crfa-cardano-donation-app
  server:
    port: 9095

donation:
  # EPOCH or SUPER_EPOCH
  cadence: EPOCH
  entities:
    cardano-fans: 0
    ktorZ: 0

entities:

  cardano-fans:
    name: cardano-fans
    address: addr1q8nq8wdhrpq402qj4hyn5rxn624l0ccua8k3epl2xl3fz57zddeldn7syvs5x2uvuefk66azhr7lelrj423lxapuxkksknwfdj

  ktorZ:
    name: ktorZ
    address: addr1g8alec26en95yzvzwpxfukglsw4nx9wrx99p3m8k2drwppvzj2enszcqyu9ps2

dryRunMode: false
env: testnet
projectId: testnetSSuaIDKnuNpFY8YdWlEc2ToOFXY4CJB7
walletFilename: .crfa-donation-app-wallet-testnet.dat
dbPath: crfa-cardano-donation-app-testnet-dev.db
