micronaut:
  application:
    name: crfa-cardano-donation-app
  server:
    port: 9095

donation:
  # EPOCH or SUPER_EPOCH
  cadence: EPOCH
  entities:
    test-wallet1: 1
  donor: anonymous

entities:
  test-wallet1:
    name: test-wallet1
    address: addr_test1qrer5vurzl4krj7tlwvqy0kgtad8r53uug5276868xshcfkz2uggmz3kw8kt7yvkzue02nhfk6mhqjmta85qsd5etjzsmf3sfw

dryRunMode: false
env: testnet
projectId: <FILL_YOUR_BLOCKFROST_PROJECT_ID>
walletFilename: .crfa-donation-app-wallet-testnet.dat
dbPath: crfa-cardano-donation-app-testnet.db
